"""add default value for is_active in games table

Revision ID: 05f4116d73ea
Revises: 2049aeebd2f0
Create Date: 2025-04-23 21:02:41.367009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05f4116d73ea'
down_revision: Union[str, None] = '2049aeebd2f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
