"""create table questions and answers __rounds

Revision ID: 19f82ee75de9
Revises: df4797fb05b3
Create Date: 2025-04-16 01:18:48.428258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19f82ee75de9'
down_revision: Union[str, None] = 'df4797fb05b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
