"""create table questions and answers __rounds

Revision ID: 699ea985e114
Revises: af50b5e6aa2d
Create Date: 2025-04-16 01:23:59.830912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '699ea985e114'
down_revision: Union[str, None] = 'af50b5e6aa2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
