"""edit game_round table

Revision ID: 790966c8e3c7
Revises: 400b115716b6
Create Date: 2025-04-21 22:46:10.766812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '790966c8e3c7'
down_revision: Union[str, None] = '400b115716b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('game_rounds_question_id_fkey', 'game_rounds', type_='foreignkey')
    op.create_foreign_key(None, 'game_rounds', 'round_questions', ['question_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game_rounds', type_='foreignkey')
    op.create_foreign_key('game_rounds_question_id_fkey', 'game_rounds', 'questions', ['question_id'], ['id'])
    # ### end Alembic commands ###
