"""create table questions and answers __rounds

Revision ID: 93b5d80d544d
Revises: 19f82ee75de9
Create Date: 2025-04-16 01:20:13.062448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93b5d80d544d'
down_revision: Union[str, None] = '19f82ee75de9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
