"""create table questions and answers __rounds

Revision ID: af50b5e6aa2d
Revises: 93b5d80d544d
Create Date: 2025-04-16 01:23:07.509169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af50b5e6aa2d'
down_revision: Union[str, None] = '93b5d80d544d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
