"""create table questions and answers __rounds

Revision ID: df4797fb05b3
Revises: f303fbebcf06
Create Date: 2025-04-16 01:17:39.935067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df4797fb05b3'
down_revision: Union[str, None] = 'f303fbebcf06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('round_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('is_found', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['game_rounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('round_question_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_question_id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('is_found', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ),
    sa.ForeignKeyConstraint(['round_question_id'], ['round_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('round_question_answers')
    op.drop_table('round_questions')
    # ### end Alembic commands ###
