"""edit game_round table

Revision ID: ebe3de5f6e28
Revises: 1c405b6f71f2
Create Date: 2025-04-21 22:52:41.210321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebe3de5f6e28'
down_revision: Union[str, None] = '1c405b6f71f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('game_rounds_question_id_fkey', 'game_rounds', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('game_rounds_question_id_fkey', 'game_rounds', 'round_questions', ['question_id'], ['id'])
    # ### end Alembic commands ###
